dist: trusty
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
on:
  tags: true
addons:
  postgresql: "9.3"
env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master
matrix:
  include:
    - python: 2.7
      env: DJANGO=1.11

    - python: 3.4
      env: DJANGO=1.11
    - python: 3.5
      env: DJANGO=1.11
    - python: 3.6
      env: DJANGO=1.11
    - python: 3.7
      env: DJANGO=1.11

    - python: 3.4
      env: DJANGO=2.0
    - python: 3.5
      env: DJANGO=2.0
    - python: 3.6
      env: DJANGO=2.0
    - python: 3.7
      env: DJANGO=2.0

    - python: 3.5
      env: DJANGO=2.1
    - python: 3.6
      env: DJANGO=2.1
    - python: 3.7
      env: DJANGO=2.1

    - python: 3.5
      env: DJANGO=master
    - python: 3.6
      env: DJANGO=master
    - python: 3.7
      env: DJANGO=master

  allow_failures:
    - python: 3.5
      env: DJANGO=master
    - python: 3.6
      env: DJANGO=master
    - python: 3.7
      env: DJANGO=master

    - python: 3.7
      env: DJANGO=1.7
    - python: 3.7
      env: DJANGO=1.8
    - python: 3.7
      env: DJANGO=1.9
    - python: 3.7
      env: DJANGO=1.10
    - python: 3.7
      env: DJANGO=1.11
    - python: 3.7
      env: DJANGO=2.0
    - python: 3.7
      env: DJANGO=2.1
    - python: 3.7
      env: DJANGO=master

install:
  - pip install tox-travis
before_script:
  - psql -U postgres -c "CREATE ROLE djangorandomqueryset LOGIN SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE djangorandomqueryset OWNER djangorandomqueryset"
script:
  - tox
