dist: bionic
language: python
cache: pip
on:
  tags: true
addons:
  postgresql: "10"
matrix:
  include:
  - python: "2.7"
    env: DJANGO=1.11

  - python: "3.6"
    env: DJANGO=1.11
  - python: "3.6"
    env: DJANGO=2.0
  - python: "3.6"
    env: DJANGO=2.1
  - python: "3.6"
    env: DJANGO=2.2
  - python: "3.6"
    env: DJANGO=master

  - python: "3.7"
    env: DJANGO=1.11
  - python: "3.7"
    env: DJANGO=2.0
  - python: "3.7"
    env: DJANGO=2.1
  - python: "3.7"
    env: DJANGO=2.2
  - python: "3.7"
    env: DJANGO=master

  allow_failures:
  - python: "3.6"
    env: DJANGO=master
  - python: "3.7"
    env: DJANGO=master

install:
  - pip install tox-travis
before_script:
  - psql -U postgres -c "CREATE ROLE django_random_queryset LOGIN SUPERUSER"
  - psql -U postgres -c "CREATE DATABASE django_random_queryset OWNER django_random_queryset"
script:
  - tox
